# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454d7673df55493e5d85f05082570ca52e1aaf2304ede42819ce50e62517f2537f316b1ad988da7daf5c40bd6cfc0991e2748cacc87e337274d19a9b1f887a26

test:
  secret_key_base: 6ba2569ace53e03de96ebf689946d4c3df53d4e7e5da5a900388e7d3c235bf0a94dce9dd3562aaead35c5442de161818f5ed966a05a0ec756f3782e7735c4787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
